### ISSUE TITLE
Can't run test in python3

### ISSUE THREAD

**Issue by JulienPalard** [bmcorser/py-multihash#2]
It's probably known, and I don't master py.test, but:

```
mandark@silence:master$ python3 setup.py test
running test
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    cmdclass={'test': PyTest},
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 15, in finalize_options
    self.test_args = []
AttributeError: can't set attribute
```

But according to the [py.test doc](http://pytest.org/latest/goodpractises.html#integrating-with-setuptools-python-setup-py-test) they put nothing in the finalize_options, so I tried to completly remove it (putting a `pass` like the `py.test` doc said hurted myself (breaking inheritance) so I just removed the method) and it worked, all test now pass.

```
diff --git a/setup.py b/setup.py
index bd50ff7..e77a7ba 100644
--- a/setup.py
+++ b/setup.py
@@ -10,11 +10,6 @@ class PyTest(TestCommand):
         TestCommand.initialize_options(self)
         self.pytest_args = []

-    def finalize_options(self):
-        TestCommand.finalize_options(self)
-        self.test_args = []
-        self.test_suite = True
-
     def run_tests(self):
         import pytest
         errno = pytest.main(self.pytest_args)
```

and ...

```
11 passed in 0.04 seconds
```

**Comment by bmcorser** [comment]
The tests run for me using an empty [pyenv virtualenv](https://github.com/yyuu/pyenv-virtualenv) with Python 3.4.2 and running `python setup.py test`

Can you tell me how you're attempting to run the suite?

**Comment by JulienPalard** [comment]
Does running `python setup.py test` uses python 3.4.2 in your pyenv-virtualenv ? I'm only having the bug running `python3 setup.py test`, distutils version `3.4.3+` from the `libpython3.4-stdlib` Debian package.

In finalize_options, self.test_args is a list, and self is a PyTest as expected, with an MRO of:

```
Method resolution order:
    PyTest
    setuptools.command.test.test
    setuptools.Command
    distutils.cmd.Command
    builtins.object
```

and the self.**setattr**.**self** returns self so I dont see any mysterious / funky "**setattr**" here,

Found it, the test_args is a property defined here `/usr/lib/python3/dist-packages/setuptools/command/test.py` from the python3-setuptools 18.4-1 Debian package:

```
@property
def test_args(self):
    return list(self._test_args())
```

So... we can't set it...

**Comment by bmcorser** [comment]
Ok, with a newer version of setuptools I reproduce this. The majority of `setup.py` came from an older version of [the py.test website](http://pytest.org/latest/goodpractises.html#integrating-with-setuptools-python-setup-py-test). I notice they have updated `:)`

**Comment by bmcorser** [comment]
Thanks for the detailed report @JulienPalard

**Comment by JulienPalard** [comment]
You're very welcome :)
